feat: Support overlay (#110)
* build(deps): use branch from craft-parts

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* feat: enable overlay feature

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: add fixture for overlay feature

* build(deps): use craft-parts 2.7.0

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* feat: refine overlay usage

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* chore: ignore every spread reuse files

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: properly install packages when preparing spread backend

Make sure snapd will be ready to handle snap installation requests.

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test(spread): hold snap refreshes

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test(spread): fix debug printing

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* build(snap): add CFLAGS env to build imagecraft part

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test(spread): test overlay integration

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* build(snap): do not rely on binaries from the core

Doing was preventing the snap from working on systems other than 24.04.

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* build(snap): add dd & fallocate to the snap

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* build(deps): use merge/hybrid-commands branch of craft-application

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: add missing dir in overlay conf

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: enable both features in tests

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: integration test with using overlay feature

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test(spread): refine overlay spread test

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: no need to patch craft-parts for unit tests

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test(spread): fix disk name in complex case

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* build(deps): use craft-application main branch

Signed-off-by: Paul Mars <paul.mars@canonical.com>

* test: warn superuser privileges are not checked in integration tests

Signed-off-by: Paul Mars <paul.mars@canonical.com>

---------

Signed-off-by: Paul Mars <paul.mars@canonical.com>

diff --git a/spread.yaml b/spread.yaml
--- a/spread.yaml
+++ b/spread.yaml
@@ -95,12 +95,16 @@ prepare: |
       cat "$tempfile"
       exit 1
   fi
-  apt install -y snapd libc6-dev git make
+  tests.pkgs install snapd libc6-dev git make
   if [[ ! "$SPREAD_BACKEND" == *-arm ]]; then
-      apt install -y gcc-multilib binfmt-support qemu-user-static
+      tests.pkgs install gcc-multilib binfmt-support qemu-user-static
   fi
 
-  snap install core24
+  snap wait system seed.loaded
+
+  # The /snap directory does not exist in some environments
+  [ ! -d /snap ] && ln -s /var/lib/snapd/snap /snap
+
   snap install yq
 
   # Setup lxd
@@ -111,13 +115,31 @@ prepare: |
     tests.pkgs remove lxd
   fi
   snap install lxd --channel=latest/stable
+
+  # Hold snap refreshes for 24h.
+  snap set system refresh.hold="$(date --date=tomorrow +%Y-%m-%dT%H:%M:%S%:z)"
+  if ! snap watch --last=auto-refresh?; then
+      journalctl -xe
+  fi
+  if ! snap watch --last=install?; then
+      journalctl -xe
+  fi
+
   lxd waitready --timeout=30
   lxd init --auto
 
   snap install --classic --dangerous imagecraft_*.snap
 
-debug: |
-  cat /root/.local/state/snapcraft/log/snapcraft-*.log
+debug-each: |
+  # output latest imagecraft log file on test failure
+  imagecraft_log_file=$(find /root/.local/state/imagecraft/log/ -name 'imagecraft*.log' | sort -n | tail -n1)
+  if [[ -f $imagecraft_log_file ]]; then
+    echo -e "imagecraft log file contents:\n----------------------------"
+    cat "$imagecraft_log_file"
+    echo "----------------------------"
+  else
+    echo "could not find imagecraft log file (this is not necessarily an error)"
+  fi
 
 suites:
   tests/spread/commons/:
